/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1alpha1 "github.com/kubeedge/api/apis/apps/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EdgeApplicationLister helps list EdgeApplications.
// All objects returned here must be treated as read-only.
type EdgeApplicationLister interface {
	// List lists all EdgeApplications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.EdgeApplication, err error)
	// EdgeApplications returns an object that can list and get EdgeApplications.
	EdgeApplications(namespace string) EdgeApplicationNamespaceLister
	EdgeApplicationListerExpansion
}

// edgeApplicationLister implements the EdgeApplicationLister interface.
type edgeApplicationLister struct {
	listers.ResourceIndexer[*appsv1alpha1.EdgeApplication]
}

// NewEdgeApplicationLister returns a new EdgeApplicationLister.
func NewEdgeApplicationLister(indexer cache.Indexer) EdgeApplicationLister {
	return &edgeApplicationLister{listers.New[*appsv1alpha1.EdgeApplication](indexer, appsv1alpha1.Resource("edgeapplication"))}
}

// EdgeApplications returns an object that can list and get EdgeApplications.
func (s *edgeApplicationLister) EdgeApplications(namespace string) EdgeApplicationNamespaceLister {
	return edgeApplicationNamespaceLister{listers.NewNamespaced[*appsv1alpha1.EdgeApplication](s.ResourceIndexer, namespace)}
}

// EdgeApplicationNamespaceLister helps list and get EdgeApplications.
// All objects returned here must be treated as read-only.
type EdgeApplicationNamespaceLister interface {
	// List lists all EdgeApplications in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.EdgeApplication, err error)
	// Get retrieves the EdgeApplication from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1alpha1.EdgeApplication, error)
	EdgeApplicationNamespaceListerExpansion
}

// edgeApplicationNamespaceLister implements the EdgeApplicationNamespaceLister
// interface.
type edgeApplicationNamespaceLister struct {
	listers.ResourceIndexer[*appsv1alpha1.EdgeApplication]
}
