/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	relaysv1 "relayv2/pkg/apis/relays/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRelayrcs implements RelayrcInterface
type FakeRelayrcs struct {
	Fake *FakeRelaysV1
	ns   string
}

var relayrcsResource = schema.GroupVersionResource{Group: "relays.kubeedge.io", Version: "v1", Resource: "relayrcs"}

var relayrcsKind = schema.GroupVersionKind{Group: "relays.kubeedge.io", Version: "v1", Kind: "Relayrc"}

// Get takes name of the relayrc, and returns the corresponding relayrc object, and an error if there is any.
func (c *FakeRelayrcs) Get(ctx context.Context, name string, options v1.GetOptions) (result *relaysv1.Relayrc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(relayrcsResource, c.ns, name), &relaysv1.Relayrc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*relaysv1.Relayrc), err
}

// List takes label and field selectors, and returns the list of Relayrcs that match those selectors.
func (c *FakeRelayrcs) List(ctx context.Context, opts v1.ListOptions) (result *relaysv1.RelayrcList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(relayrcsResource, relayrcsKind, c.ns, opts), &relaysv1.RelayrcList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &relaysv1.RelayrcList{ListMeta: obj.(*relaysv1.RelayrcList).ListMeta}
	for _, item := range obj.(*relaysv1.RelayrcList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested relayrcs.
func (c *FakeRelayrcs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(relayrcsResource, c.ns, opts))

}

// Create takes the representation of a relayrc and creates it.  Returns the server's representation of the relayrc, and an error, if there is any.
func (c *FakeRelayrcs) Create(ctx context.Context, relayrc *relaysv1.Relayrc, opts v1.CreateOptions) (result *relaysv1.Relayrc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(relayrcsResource, c.ns, relayrc), &relaysv1.Relayrc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*relaysv1.Relayrc), err
}

// Update takes the representation of a relayrc and updates it. Returns the server's representation of the relayrc, and an error, if there is any.
func (c *FakeRelayrcs) Update(ctx context.Context, relayrc *relaysv1.Relayrc, opts v1.UpdateOptions) (result *relaysv1.Relayrc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(relayrcsResource, c.ns, relayrc), &relaysv1.Relayrc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*relaysv1.Relayrc), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRelayrcs) UpdateStatus(ctx context.Context, relayrc *relaysv1.Relayrc, opts v1.UpdateOptions) (*relaysv1.Relayrc, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(relayrcsResource, "status", c.ns, relayrc), &relaysv1.Relayrc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*relaysv1.Relayrc), err
}

// Delete takes name of the relayrc and deletes it. Returns an error if one occurs.
func (c *FakeRelayrcs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(relayrcsResource, c.ns, name), &relaysv1.Relayrc{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRelayrcs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(relayrcsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &relaysv1.RelayrcList{})
	return err
}

// Patch applies the patch and returns the patched relayrc.
func (c *FakeRelayrcs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *relaysv1.Relayrc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(relayrcsResource, c.ns, name, pt, data, subresources...), &relaysv1.Relayrc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*relaysv1.Relayrc), err
}
