/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/kubeedge/api/apis/operations/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ConfigUpdateJobLister helps list ConfigUpdateJobs.
// All objects returned here must be treated as read-only.
type ConfigUpdateJobLister interface {
	// List lists all ConfigUpdateJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.ConfigUpdateJob, err error)
	// Get retrieves the ConfigUpdateJob from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.ConfigUpdateJob, error)
	ConfigUpdateJobListerExpansion
}

// configUpdateJobLister implements the ConfigUpdateJobLister interface.
type configUpdateJobLister struct {
	indexer cache.Indexer
}

// NewConfigUpdateJobLister returns a new ConfigUpdateJobLister.
func NewConfigUpdateJobLister(indexer cache.Indexer) ConfigUpdateJobLister {
	return &configUpdateJobLister{indexer: indexer}
}

// List lists all ConfigUpdateJobs in the indexer.
func (s *configUpdateJobLister) List(selector labels.Selector) (ret []*v1alpha2.ConfigUpdateJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.ConfigUpdateJob))
	})
	return ret, err
}

// Get retrieves the ConfigUpdateJob from the index for a given name.
func (s *configUpdateJobLister) Get(name string) (*v1alpha2.ConfigUpdateJob, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("configupdatejob"), name)
	}
	return obj.(*v1alpha2.ConfigUpdateJob), nil
}
