/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kubeedge/api/apis/reliablesyncs/v1alpha1"
	scheme "github.com/kubeedge/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ObjectSyncsGetter has a method to return a ObjectSyncInterface.
// A group's client should implement this interface.
type ObjectSyncsGetter interface {
	ObjectSyncs(namespace string) ObjectSyncInterface
}

// ObjectSyncInterface has methods to work with ObjectSync resources.
type ObjectSyncInterface interface {
	Create(ctx context.Context, objectSync *v1alpha1.ObjectSync, opts v1.CreateOptions) (*v1alpha1.ObjectSync, error)
	Update(ctx context.Context, objectSync *v1alpha1.ObjectSync, opts v1.UpdateOptions) (*v1alpha1.ObjectSync, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, objectSync *v1alpha1.ObjectSync, opts v1.UpdateOptions) (*v1alpha1.ObjectSync, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ObjectSync, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ObjectSyncList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ObjectSync, err error)
	ObjectSyncExpansion
}

// objectSyncs implements ObjectSyncInterface
type objectSyncs struct {
	*gentype.ClientWithList[*v1alpha1.ObjectSync, *v1alpha1.ObjectSyncList]
}

// newObjectSyncs returns a ObjectSyncs
func newObjectSyncs(c *ReliablesyncsV1alpha1Client, namespace string) *objectSyncs {
	return &objectSyncs{
		gentype.NewClientWithList[*v1alpha1.ObjectSync, *v1alpha1.ObjectSyncList](
			"objectsyncs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.ObjectSync { return &v1alpha1.ObjectSync{} },
			func() *v1alpha1.ObjectSyncList { return &v1alpha1.ObjectSyncList{} }),
	}
}
