/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: google/protobuf/wrappers.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "google/protobuf/wrappers.pb-c.h"
void   google__protobuf__double_value__init
                     (Google__Protobuf__DoubleValue         *message)
{
  static const Google__Protobuf__DoubleValue init_value = GOOGLE__PROTOBUF__DOUBLE_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__double_value__get_packed_size
                     (const Google__Protobuf__DoubleValue *message)
{
  assert(message->base.descriptor == &google__protobuf__double_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__double_value__pack
                     (const Google__Protobuf__DoubleValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__double_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__double_value__pack_to_buffer
                     (const Google__Protobuf__DoubleValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__double_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__DoubleValue *
       google__protobuf__double_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__DoubleValue *)
     protobuf_c_message_unpack (&google__protobuf__double_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__double_value__free_unpacked
                     (Google__Protobuf__DoubleValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__double_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__float_value__init
                     (Google__Protobuf__FloatValue         *message)
{
  static const Google__Protobuf__FloatValue init_value = GOOGLE__PROTOBUF__FLOAT_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__float_value__get_packed_size
                     (const Google__Protobuf__FloatValue *message)
{
  assert(message->base.descriptor == &google__protobuf__float_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__float_value__pack
                     (const Google__Protobuf__FloatValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__float_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__float_value__pack_to_buffer
                     (const Google__Protobuf__FloatValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__float_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__FloatValue *
       google__protobuf__float_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__FloatValue *)
     protobuf_c_message_unpack (&google__protobuf__float_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__float_value__free_unpacked
                     (Google__Protobuf__FloatValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__float_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__int64_value__init
                     (Google__Protobuf__Int64Value         *message)
{
  static const Google__Protobuf__Int64Value init_value = GOOGLE__PROTOBUF__INT64_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__int64_value__get_packed_size
                     (const Google__Protobuf__Int64Value *message)
{
  assert(message->base.descriptor == &google__protobuf__int64_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__int64_value__pack
                     (const Google__Protobuf__Int64Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__int64_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__int64_value__pack_to_buffer
                     (const Google__Protobuf__Int64Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__int64_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__Int64Value *
       google__protobuf__int64_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__Int64Value *)
     protobuf_c_message_unpack (&google__protobuf__int64_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__int64_value__free_unpacked
                     (Google__Protobuf__Int64Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__int64_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__uint64_value__init
                     (Google__Protobuf__UInt64Value         *message)
{
  static const Google__Protobuf__UInt64Value init_value = GOOGLE__PROTOBUF__UINT64_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__uint64_value__get_packed_size
                     (const Google__Protobuf__UInt64Value *message)
{
  assert(message->base.descriptor == &google__protobuf__uint64_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__uint64_value__pack
                     (const Google__Protobuf__UInt64Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__uint64_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__uint64_value__pack_to_buffer
                     (const Google__Protobuf__UInt64Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__uint64_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__UInt64Value *
       google__protobuf__uint64_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__UInt64Value *)
     protobuf_c_message_unpack (&google__protobuf__uint64_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__uint64_value__free_unpacked
                     (Google__Protobuf__UInt64Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__uint64_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__int32_value__init
                     (Google__Protobuf__Int32Value         *message)
{
  static const Google__Protobuf__Int32Value init_value = GOOGLE__PROTOBUF__INT32_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__int32_value__get_packed_size
                     (const Google__Protobuf__Int32Value *message)
{
  assert(message->base.descriptor == &google__protobuf__int32_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__int32_value__pack
                     (const Google__Protobuf__Int32Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__int32_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__int32_value__pack_to_buffer
                     (const Google__Protobuf__Int32Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__int32_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__Int32Value *
       google__protobuf__int32_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__Int32Value *)
     protobuf_c_message_unpack (&google__protobuf__int32_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__int32_value__free_unpacked
                     (Google__Protobuf__Int32Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__int32_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__uint32_value__init
                     (Google__Protobuf__UInt32Value         *message)
{
  static const Google__Protobuf__UInt32Value init_value = GOOGLE__PROTOBUF__UINT32_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__uint32_value__get_packed_size
                     (const Google__Protobuf__UInt32Value *message)
{
  assert(message->base.descriptor == &google__protobuf__uint32_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__uint32_value__pack
                     (const Google__Protobuf__UInt32Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__uint32_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__uint32_value__pack_to_buffer
                     (const Google__Protobuf__UInt32Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__uint32_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__UInt32Value *
       google__protobuf__uint32_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__UInt32Value *)
     protobuf_c_message_unpack (&google__protobuf__uint32_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__uint32_value__free_unpacked
                     (Google__Protobuf__UInt32Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__uint32_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__bool_value__init
                     (Google__Protobuf__BoolValue         *message)
{
  static const Google__Protobuf__BoolValue init_value = GOOGLE__PROTOBUF__BOOL_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__bool_value__get_packed_size
                     (const Google__Protobuf__BoolValue *message)
{
  assert(message->base.descriptor == &google__protobuf__bool_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__bool_value__pack
                     (const Google__Protobuf__BoolValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__bool_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__bool_value__pack_to_buffer
                     (const Google__Protobuf__BoolValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__bool_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__BoolValue *
       google__protobuf__bool_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__BoolValue *)
     protobuf_c_message_unpack (&google__protobuf__bool_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__bool_value__free_unpacked
                     (Google__Protobuf__BoolValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__bool_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__string_value__init
                     (Google__Protobuf__StringValue         *message)
{
  static const Google__Protobuf__StringValue init_value = GOOGLE__PROTOBUF__STRING_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__string_value__get_packed_size
                     (const Google__Protobuf__StringValue *message)
{
  assert(message->base.descriptor == &google__protobuf__string_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__string_value__pack
                     (const Google__Protobuf__StringValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__string_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__string_value__pack_to_buffer
                     (const Google__Protobuf__StringValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__string_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__StringValue *
       google__protobuf__string_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__StringValue *)
     protobuf_c_message_unpack (&google__protobuf__string_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__string_value__free_unpacked
                     (Google__Protobuf__StringValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__string_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__bytes_value__init
                     (Google__Protobuf__BytesValue         *message)
{
  static const Google__Protobuf__BytesValue init_value = GOOGLE__PROTOBUF__BYTES_VALUE__INIT;
  *message = init_value;
}
size_t google__protobuf__bytes_value__get_packed_size
                     (const Google__Protobuf__BytesValue *message)
{
  assert(message->base.descriptor == &google__protobuf__bytes_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__bytes_value__pack
                     (const Google__Protobuf__BytesValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__bytes_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__bytes_value__pack_to_buffer
                     (const Google__Protobuf__BytesValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__bytes_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__BytesValue *
       google__protobuf__bytes_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__BytesValue *)
     protobuf_c_message_unpack (&google__protobuf__bytes_value__descriptor,
                                allocator, len, data);
}
void   google__protobuf__bytes_value__free_unpacked
                     (Google__Protobuf__BytesValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__bytes_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor google__protobuf__double_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__DoubleValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__double_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__double_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__double_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.DoubleValue",
  "DoubleValue",
  "Google__Protobuf__DoubleValue",
  "google.protobuf",
  sizeof(Google__Protobuf__DoubleValue),
  1,
  google__protobuf__double_value__field_descriptors,
  google__protobuf__double_value__field_indices_by_name,
  1,  google__protobuf__double_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__double_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__float_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__FloatValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__float_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__float_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__float_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.FloatValue",
  "FloatValue",
  "Google__Protobuf__FloatValue",
  "google.protobuf",
  sizeof(Google__Protobuf__FloatValue),
  1,
  google__protobuf__float_value__field_descriptors,
  google__protobuf__float_value__field_indices_by_name,
  1,  google__protobuf__float_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__float_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__int64_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__Int64Value, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__int64_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__int64_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__int64_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.Int64Value",
  "Int64Value",
  "Google__Protobuf__Int64Value",
  "google.protobuf",
  sizeof(Google__Protobuf__Int64Value),
  1,
  google__protobuf__int64_value__field_descriptors,
  google__protobuf__int64_value__field_indices_by_name,
  1,  google__protobuf__int64_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__int64_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__uint64_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__UInt64Value, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__uint64_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__uint64_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__uint64_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.UInt64Value",
  "UInt64Value",
  "Google__Protobuf__UInt64Value",
  "google.protobuf",
  sizeof(Google__Protobuf__UInt64Value),
  1,
  google__protobuf__uint64_value__field_descriptors,
  google__protobuf__uint64_value__field_indices_by_name,
  1,  google__protobuf__uint64_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__uint64_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__int32_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__Int32Value, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__int32_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__int32_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__int32_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.Int32Value",
  "Int32Value",
  "Google__Protobuf__Int32Value",
  "google.protobuf",
  sizeof(Google__Protobuf__Int32Value),
  1,
  google__protobuf__int32_value__field_descriptors,
  google__protobuf__int32_value__field_indices_by_name,
  1,  google__protobuf__int32_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__int32_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__uint32_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__UInt32Value, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__uint32_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__uint32_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__uint32_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.UInt32Value",
  "UInt32Value",
  "Google__Protobuf__UInt32Value",
  "google.protobuf",
  sizeof(Google__Protobuf__UInt32Value),
  1,
  google__protobuf__uint32_value__field_descriptors,
  google__protobuf__uint32_value__field_indices_by_name,
  1,  google__protobuf__uint32_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__uint32_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__bool_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__BoolValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__bool_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__bool_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__bool_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.BoolValue",
  "BoolValue",
  "Google__Protobuf__BoolValue",
  "google.protobuf",
  sizeof(Google__Protobuf__BoolValue),
  1,
  google__protobuf__bool_value__field_descriptors,
  google__protobuf__bool_value__field_indices_by_name,
  1,  google__protobuf__bool_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__bool_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__string_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__StringValue, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__string_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__string_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__string_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.StringValue",
  "StringValue",
  "Google__Protobuf__StringValue",
  "google.protobuf",
  sizeof(Google__Protobuf__StringValue),
  1,
  google__protobuf__string_value__field_descriptors,
  google__protobuf__string_value__field_indices_by_name,
  1,  google__protobuf__string_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__string_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__bytes_value__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Google__Protobuf__BytesValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__protobuf__bytes_value__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__protobuf__bytes_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__bytes_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.BytesValue",
  "BytesValue",
  "Google__Protobuf__BytesValue",
  "google.protobuf",
  sizeof(Google__Protobuf__BytesValue),
  1,
  google__protobuf__bytes_value__field_descriptors,
  google__protobuf__bytes_value__field_indices_by_name,
  1,  google__protobuf__bytes_value__number_ranges,
  (ProtobufCMessageInit) google__protobuf__bytes_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
