/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kubeedge/api/apis/devices/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDeviceStatuses implements DeviceStatusInterface
type FakeDeviceStatuses struct {
	Fake *FakeDevicesV1beta1
	ns   string
}

var devicestatusesResource = v1beta1.SchemeGroupVersion.WithResource("devicestatuses")

var devicestatusesKind = v1beta1.SchemeGroupVersion.WithKind("DeviceStatus")

// Get takes name of the deviceStatus, and returns the corresponding deviceStatus object, and an error if there is any.
func (c *FakeDeviceStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.DeviceStatus, err error) {
	emptyResult := &v1beta1.DeviceStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(devicestatusesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DeviceStatus), err
}

// List takes label and field selectors, and returns the list of DeviceStatuses that match those selectors.
func (c *FakeDeviceStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.DeviceStatusList, err error) {
	emptyResult := &v1beta1.DeviceStatusList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(devicestatusesResource, devicestatusesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.DeviceStatusList{ListMeta: obj.(*v1beta1.DeviceStatusList).ListMeta}
	for _, item := range obj.(*v1beta1.DeviceStatusList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested deviceStatuses.
func (c *FakeDeviceStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(devicestatusesResource, c.ns, opts))

}

// Create takes the representation of a deviceStatus and creates it.  Returns the server's representation of the deviceStatus, and an error, if there is any.
func (c *FakeDeviceStatuses) Create(ctx context.Context, deviceStatus *v1beta1.DeviceStatus, opts v1.CreateOptions) (result *v1beta1.DeviceStatus, err error) {
	emptyResult := &v1beta1.DeviceStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(devicestatusesResource, c.ns, deviceStatus, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DeviceStatus), err
}

// Update takes the representation of a deviceStatus and updates it. Returns the server's representation of the deviceStatus, and an error, if there is any.
func (c *FakeDeviceStatuses) Update(ctx context.Context, deviceStatus *v1beta1.DeviceStatus, opts v1.UpdateOptions) (result *v1beta1.DeviceStatus, err error) {
	emptyResult := &v1beta1.DeviceStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(devicestatusesResource, c.ns, deviceStatus, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DeviceStatus), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDeviceStatuses) UpdateStatus(ctx context.Context, deviceStatus *v1beta1.DeviceStatus, opts v1.UpdateOptions) (result *v1beta1.DeviceStatus, err error) {
	emptyResult := &v1beta1.DeviceStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(devicestatusesResource, "status", c.ns, deviceStatus, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DeviceStatus), err
}

// Delete takes name of the deviceStatus and deletes it. Returns an error if one occurs.
func (c *FakeDeviceStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(devicestatusesResource, c.ns, name, opts), &v1beta1.DeviceStatus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDeviceStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(devicestatusesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.DeviceStatusList{})
	return err
}

// Patch applies the patch and returns the patched deviceStatus.
func (c *FakeDeviceStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.DeviceStatus, err error) {
	emptyResult := &v1beta1.DeviceStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(devicestatusesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DeviceStatus), err
}
