/*
Copyright 2019 The Kubeedge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package cmd

import (
	"fmt"
	"io"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/kubeedge/kubeedge/keadm/app/cmd/options"
	"github.com/kubeedge/kubeedge/keadm/app/cmd/util"
)

var (
	edgeJoinLongDescription = `
"kubeedge join" command bootstraps KubeEdge's edge component.
It checks if the pre-requisites are installed already,
If not installed, this command will help in download,
install and execute on the host.
It will also connect with cloud component to receieve 
further instructions and forward telemetry data from 
devices to cloud
`
	edgeJoinExample = `
kubeedge join --server=<ip:port>

  - For this command --server option is a Mandatory option
  - This command will download and install the default version of pre-requisites and KubeEdge

kubeedge join --server=10.20.30.40:8080 --docker-version= --kubeedge-version=0.2.1 --kubernetes-version=1.14.1
kubeedge join --server=10.20.30.40:8080 --docker-version --kubeedge-version=0.2.1 --kubernetes-version=1.14.1

  - In case, any option is used in a format like as shown for "--docker-version" or "--docker-version=", without a value
		then default values will be used. 
		Also options like "--docker-version", "--kubernetes-version" and "--kubeedge-version", version should be in 
		format like "18.06.3", "1.14.0" and "0.2.1".
`
)

// NewEdgeJoin returns KubeEdge edge join command.
func NewEdgeJoin(out io.Writer, joinOptions *options.JoinOptions) *cobra.Command {
	if joinOptions == nil {
		joinOptions = newJoinOptions()
	}

	tools := make(map[string]util.ToolsInstaller, 0)
	flagVals := make(map[string]util.FlagData, 0)

	cmd := &cobra.Command{
		Use:     "join",
		Short:   "Bootstraps edge component. Checks and install (if required) the pre-requisites.\nExecute it on any edge node machine you wish to join",
		Long:    edgeJoinLongDescription,
		Example: edgeJoinExample,
		PreRunE: func(cmd *cobra.Command, args []string) error {

			whoRunning, err := util.IsKubeEdgeController()
			if err != nil {
				return err
			}
			if util.KubeEdgeCloudRunning == whoRunning {
				return fmt.Errorf("This is KubeEdge Cloud node, KubeEdge Edge node should't be initialised on it")
			}
			return nil
		},
		Run: func(cmd *cobra.Command, args []string) {

			//Visit all the flags and store their values and default values.
			checkFlags := func(f *pflag.Flag) {
				util.AddToolVals(f, flagVals)
			}
			cmd.Flags().VisitAll(checkFlags)

			Add2ToolsList(tools, flagVals, joinOptions)
			Execute(tools)
		},
	}

	addJoinOtherFlags(cmd, joinOptions)
	return cmd
}

func addJoinOtherFlags(cmd *cobra.Command, joinOptions *options.JoinOptions) {

	cmd.Flags().StringVar(&joinOptions.KubeEdgeVersion, options.KubeEdgeVersion, joinOptions.KubeEdgeVersion,
		"Use this key to download and use the required KubeEdge version")
	cmd.Flags().Lookup(options.KubeEdgeVersion).NoOptDefVal = joinOptions.KubeEdgeVersion

	cmd.Flags().StringVar(&joinOptions.DockerVersion, options.DockerVersion, joinOptions.DockerVersion,
		"Use this key to download and use the required Docker version")
	cmd.Flags().Lookup(options.DockerVersion).NoOptDefVal = joinOptions.DockerVersion

	cmd.Flags().StringVar(&joinOptions.KubernetesVersion, options.KubernetesVersion, joinOptions.KubernetesVersion,
		"Use this key to download and use the required Kubernetes version")
	cmd.Flags().Lookup(options.KubernetesVersion).NoOptDefVal = joinOptions.KubernetesVersion

	cmd.Flags().StringVarP(&joinOptions.K8SAPIServerIPPort, options.K8SAPIServerIPPort, "s", joinOptions.K8SAPIServerIPPort,
		"IP:Port address of cloud components host/VM")
	cmd.MarkFlagRequired(options.K8SAPIServerIPPort)

	//Commenting the certificate for path option now, as they are placed in /etc/kubedge/certs by default by gen script.
	// cmd.Flags().StringVar(&joinOptions.CertPath, options.CertPath, joinOptions.CertPath,
	// 	"Downloaded path of the certifcates generated by cloud component in this host")
	// cmd.Flags().Lookup(options.CertPath).NoOptDefVal = joinOptions.CertPath
}

// newJoinOptions returns a struct ready for being used for creating cmd join flags.
func newJoinOptions() *options.JoinOptions {
	opts := &options.JoinOptions{}
	opts.InitOptions = options.InitOptions{DockerVersion: options.DefaultDockerVersion, KubeEdgeVersion: options.DefaultKubeEdgeVersion,
		KubernetesVersion: options.DefaultK8SVersion}
	opts.CertPath = options.DefaultCertPath
	return opts
}

//Add2ToolsList Reads the flagData (containing val and default val) and join options to fill the list of tools.
func Add2ToolsList(toolList map[string]util.ToolsInstaller, flagData map[string]util.FlagData, joinOptions *options.JoinOptions) {

	var kubeVer, dockerVer, k8sVer string

	flgData, ok := flagData[options.KubeEdgeVersion]
	if ok {
		kubeVer = util.CheckIfAvailable(flgData.Val.(string), flgData.DefVal.(string))
	} else {
		kubeVer = joinOptions.KubeEdgeVersion
	}
	toolList["KubeEdge"] = &util.KubeEdgeInstTool{Common: util.Common{ToolVersion: kubeVer}, K8SApiServerIP: joinOptions.K8SAPIServerIPPort}

	flgData, ok = flagData[options.DockerVersion]
	if ok {
		dockerVer = util.CheckIfAvailable(flgData.Val.(string), flgData.DefVal.(string))
	} else {
		dockerVer = joinOptions.DockerVersion
	}
	toolList["Docker"] = &util.DockerInstTool{Common: util.Common{ToolVersion: dockerVer}, DefaultToolVer: flgData.DefVal.(string)}

	flgData, ok = flagData[options.KubernetesVersion]
	if ok {
		k8sVer = util.CheckIfAvailable(flgData.Val.(string), flgData.DefVal.(string))
	} else {
		k8sVer = joinOptions.KubernetesVersion
	}
	toolList["Kubernetes"] = &util.K8SInstTool{Common: util.Common{ToolVersion: k8sVer}, IsEdgeNode: true, DefaultToolVer: flgData.DefVal.(string)}
	toolList["MQTT"] = &util.MQTTInstTool{}
}

//Execute the instalation for each tool and start edge_core
func Execute(toolList map[string]util.ToolsInstaller) {

	//Install all the required pre-requisite tools
	for name, tool := range toolList {
		if name != "KubeEdge" {
			err := tool.InstallTools()
			if err != nil {
				fmt.Println(err.Error())
				continue
			}
		}
	}

	//Install and Start KubeEdge Node
	err := toolList["KubeEdge"].InstallTools()
	if err != nil {
		fmt.Println(err.Error())
	}
}
