{{- if (.Values.controllerManager.enable) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: {{ .Release.Namespace }}
  {{- with .Values.controllerManager.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-manager
  {{- with .Values.controllerManager.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller-manager
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-manager
  {{- with .Values.controllerManager.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["apps.kubeedge.io"]
    resources: ["nodegroups", "nodegroups/status"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "patch", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch", "get", "delete"]
  - apiGroups: ["apps.kubeedge.io"]
    resources: ["edgeapplications", "edgeapplications/status"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch", "create", "update", "patch", "delete", "get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "watch", "create", "update", "patch", "delete", "get"]
  - apiGroups: ["operations.kubeedge.io"]
    resources: ["nodeupgradejobs", "nodeupgradejobs/status", "imageprepulljobs", "imageprepulljobs/status", "configupdatejobs", "configupdatejobs/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
{{- end }}
