/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kubeedge/api/apis/policy/v1alpha1"
	scheme "github.com/kubeedge/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceAccountAccessesGetter has a method to return a ServiceAccountAccessInterface.
// A group's client should implement this interface.
type ServiceAccountAccessesGetter interface {
	ServiceAccountAccesses(namespace string) ServiceAccountAccessInterface
}

// ServiceAccountAccessInterface has methods to work with ServiceAccountAccess resources.
type ServiceAccountAccessInterface interface {
	Create(ctx context.Context, serviceAccountAccess *v1alpha1.ServiceAccountAccess, opts v1.CreateOptions) (*v1alpha1.ServiceAccountAccess, error)
	Update(ctx context.Context, serviceAccountAccess *v1alpha1.ServiceAccountAccess, opts v1.UpdateOptions) (*v1alpha1.ServiceAccountAccess, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceAccountAccess *v1alpha1.ServiceAccountAccess, opts v1.UpdateOptions) (*v1alpha1.ServiceAccountAccess, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ServiceAccountAccess, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ServiceAccountAccessList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceAccountAccess, err error)
	ServiceAccountAccessExpansion
}

// serviceAccountAccesses implements ServiceAccountAccessInterface
type serviceAccountAccesses struct {
	*gentype.ClientWithList[*v1alpha1.ServiceAccountAccess, *v1alpha1.ServiceAccountAccessList]
}

// newServiceAccountAccesses returns a ServiceAccountAccesses
func newServiceAccountAccesses(c *PolicyV1alpha1Client, namespace string) *serviceAccountAccesses {
	return &serviceAccountAccesses{
		gentype.NewClientWithList[*v1alpha1.ServiceAccountAccess, *v1alpha1.ServiceAccountAccessList](
			"serviceaccountaccesses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.ServiceAccountAccess { return &v1alpha1.ServiceAccountAccess{} },
			func() *v1alpha1.ServiceAccountAccessList { return &v1alpha1.ServiceAccountAccessList{} }),
	}
}
