/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeedge/api/apis/streamrules/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStreamRuleEndpoints implements StreamRuleEndpointInterface
type FakeStreamRuleEndpoints struct {
	Fake *FakeStreamrulesV1alpha1
	ns   string
}

var streamruleendpointsResource = v1alpha1.SchemeGroupVersion.WithResource("streamruleendpoints")

var streamruleendpointsKind = v1alpha1.SchemeGroupVersion.WithKind("StreamRuleEndpoint")

// Get takes name of the streamRuleEndpoint, and returns the corresponding streamRuleEndpoint object, and an error if there is any.
func (c *FakeStreamRuleEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StreamRuleEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(streamruleendpointsResource, c.ns, name), &v1alpha1.StreamRuleEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StreamRuleEndpoint), err
}

// List takes label and field selectors, and returns the list of StreamRuleEndpoints that match those selectors.
func (c *FakeStreamRuleEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StreamRuleEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(streamruleendpointsResource, streamruleendpointsKind, c.ns, opts), &v1alpha1.StreamRuleEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StreamRuleEndpointList{ListMeta: obj.(*v1alpha1.StreamRuleEndpointList).ListMeta}
	for _, item := range obj.(*v1alpha1.StreamRuleEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested streamRuleEndpoints.
func (c *FakeStreamRuleEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(streamruleendpointsResource, c.ns, opts))

}

// Create takes the representation of a streamRuleEndpoint and creates it.  Returns the server's representation of the streamRuleEndpoint, and an error, if there is any.
func (c *FakeStreamRuleEndpoints) Create(ctx context.Context, streamRuleEndpoint *v1alpha1.StreamRuleEndpoint, opts v1.CreateOptions) (result *v1alpha1.StreamRuleEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(streamruleendpointsResource, c.ns, streamRuleEndpoint), &v1alpha1.StreamRuleEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StreamRuleEndpoint), err
}

// Update takes the representation of a streamRuleEndpoint and updates it. Returns the server's representation of the streamRuleEndpoint, and an error, if there is any.
func (c *FakeStreamRuleEndpoints) Update(ctx context.Context, streamRuleEndpoint *v1alpha1.StreamRuleEndpoint, opts v1.UpdateOptions) (result *v1alpha1.StreamRuleEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(streamruleendpointsResource, c.ns, streamRuleEndpoint), &v1alpha1.StreamRuleEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StreamRuleEndpoint), err
}

// Delete takes name of the streamRuleEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeStreamRuleEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(streamruleendpointsResource, c.ns, name, opts), &v1alpha1.StreamRuleEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStreamRuleEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(streamruleendpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StreamRuleEndpointList{})
	return err
}

// Patch applies the patch and returns the patched streamRuleEndpoint.
func (c *FakeStreamRuleEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StreamRuleEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(streamruleendpointsResource, c.ns, name, pt, data, subresources...), &v1alpha1.StreamRuleEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StreamRuleEndpoint), err
}
