/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	devicesv1beta1 "github.com/kubeedge/api/apis/devices/v1beta1"
	scheme "github.com/kubeedge/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DeviceStatusesGetter has a method to return a DeviceStatusInterface.
// A group's client should implement this interface.
type DeviceStatusesGetter interface {
	DeviceStatuses(namespace string) DeviceStatusInterface
}

// DeviceStatusInterface has methods to work with DeviceStatus resources.
type DeviceStatusInterface interface {
	Create(ctx context.Context, deviceStatus *devicesv1beta1.DeviceStatus, opts v1.CreateOptions) (*devicesv1beta1.DeviceStatus, error)
	Update(ctx context.Context, deviceStatus *devicesv1beta1.DeviceStatus, opts v1.UpdateOptions) (*devicesv1beta1.DeviceStatus, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, deviceStatus *devicesv1beta1.DeviceStatus, opts v1.UpdateOptions) (*devicesv1beta1.DeviceStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*devicesv1beta1.DeviceStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*devicesv1beta1.DeviceStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *devicesv1beta1.DeviceStatus, err error)
	DeviceStatusExpansion
}

// deviceStatuses implements DeviceStatusInterface
type deviceStatuses struct {
	*gentype.ClientWithList[*devicesv1beta1.DeviceStatus, *devicesv1beta1.DeviceStatusList]
}

// newDeviceStatuses returns a DeviceStatuses
func newDeviceStatuses(c *DevicesV1beta1Client, namespace string) *deviceStatuses {
	return &deviceStatuses{
		gentype.NewClientWithList[*devicesv1beta1.DeviceStatus, *devicesv1beta1.DeviceStatusList](
			"devicestatuses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *devicesv1beta1.DeviceStatus { return &devicesv1beta1.DeviceStatus{} },
			func() *devicesv1beta1.DeviceStatusList { return &devicesv1beta1.DeviceStatusList{} },
		),
	}
}
