/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/kubeedge/api/apis/devices/v1beta1"
	scheme "github.com/kubeedge/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DeviceModelsGetter has a method to return a DeviceModelInterface.
// A group's client should implement this interface.
type DeviceModelsGetter interface {
	DeviceModels(namespace string) DeviceModelInterface
}

// DeviceModelInterface has methods to work with DeviceModel resources.
type DeviceModelInterface interface {
	Create(ctx context.Context, deviceModel *v1beta1.DeviceModel, opts v1.CreateOptions) (*v1beta1.DeviceModel, error)
	Update(ctx context.Context, deviceModel *v1beta1.DeviceModel, opts v1.UpdateOptions) (*v1beta1.DeviceModel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.DeviceModel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.DeviceModelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.DeviceModel, err error)
	DeviceModelExpansion
}

// deviceModels implements DeviceModelInterface
type deviceModels struct {
	*gentype.ClientWithList[*v1beta1.DeviceModel, *v1beta1.DeviceModelList]
}

// newDeviceModels returns a DeviceModels
func newDeviceModels(c *DevicesV1beta1Client, namespace string) *deviceModels {
	return &deviceModels{
		gentype.NewClientWithList[*v1beta1.DeviceModel, *v1beta1.DeviceModelList](
			"devicemodels",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.DeviceModel { return &v1beta1.DeviceModel{} },
			func() *v1beta1.DeviceModelList { return &v1beta1.DeviceModelList{} }),
	}
}
