mqtt:
  mode: 0       # 0 -internal mqtt broker  1 - external mqtt broker
  server: tcp://127.0.0.1:1883 # external mqtt broker url.
  internal-server: tcp://127.0.0.1:1884 # internal mqtt broker url.
device-name: CC2650 SensorTag
action-manager:
  actions:
    - name: IRTemperatureConfiguration
      enable: true
      property-name: temperature-enable     #property-name define in the device CRD
    - name: IRTemperatureData
      enable: false
      property-name: temperature            #property-name define in the device CRD
    - name: IOConfigurationInitialize
      enable: true
      property-name: io-config-initialize    #property-name define in the device CRD
    - name: IODataInitialize
      enable: true
      property-name: io-data-initialize      #property-name define in the device CRD
    - name: IOConfiguration
      enable: false
      property-name: io-config                #property-name define in the device CRD
    - name: IOData
      enable: false
      property-name: io-data                  #property-name define in the device CRD
scheduler:
  schedules:
    - enable: true
      name: temperature
      event-frequency: 3000
      occurrence-limit: 10            # if it is 0, then the event will execute infinitely
      actions:
        - IRTemperatureData          # Action name defined in the action-manager section
watcher:
  enable: false
  attributes :
    - name: io-data                     # the twin attribute name defined while creating device
      actions:                         # list of action names, defined in the action-manager section, to be executed on the device
        - IOConfigurationInitialize
        - IODataInitialize
        - IOConfiguration
        - IOData
