/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"

	v1alpha2 "github.com/kubeedge/api/apis/operations/v1alpha2"
	scheme "github.com/kubeedge/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ConfigUpdateJobsGetter has a method to return a ConfigUpdateJobInterface.
// A group's client should implement this interface.
type ConfigUpdateJobsGetter interface {
	ConfigUpdateJobs() ConfigUpdateJobInterface
}

// ConfigUpdateJobInterface has methods to work with ConfigUpdateJob resources.
type ConfigUpdateJobInterface interface {
	Create(ctx context.Context, configUpdateJob *v1alpha2.ConfigUpdateJob, opts v1.CreateOptions) (*v1alpha2.ConfigUpdateJob, error)
	Update(ctx context.Context, configUpdateJob *v1alpha2.ConfigUpdateJob, opts v1.UpdateOptions) (*v1alpha2.ConfigUpdateJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, configUpdateJob *v1alpha2.ConfigUpdateJob, opts v1.UpdateOptions) (*v1alpha2.ConfigUpdateJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.ConfigUpdateJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.ConfigUpdateJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.ConfigUpdateJob, err error)
	ConfigUpdateJobExpansion
}

// configUpdateJobs implements ConfigUpdateJobInterface
type configUpdateJobs struct {
	*gentype.ClientWithList[*v1alpha2.ConfigUpdateJob, *v1alpha2.ConfigUpdateJobList]
}

// newConfigUpdateJobs returns a ConfigUpdateJobs
func newConfigUpdateJobs(c *OperationsV1alpha2Client) *configUpdateJobs {
	return &configUpdateJobs{
		gentype.NewClientWithList[*v1alpha2.ConfigUpdateJob, *v1alpha2.ConfigUpdateJobList](
			"configupdatejobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha2.ConfigUpdateJob { return &v1alpha2.ConfigUpdateJob{} },
			func() *v1alpha2.ConfigUpdateJobList { return &v1alpha2.ConfigUpdateJobList{} }),
	}
}
