/*
Copyright 2019 The Kubeedge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package options

const (
	//KubeedgeVersion sets the version of KubeEdge to be used
	KubeedgeVersion = "kubeedge-version"

	//DockerVersion sets the version of Docker to be used
	DockerVersion = "docker-version"

	//Kubernetesversion sets the version of Kuberneted to be used
	Kubernetesversion = "kubernetes-version"

	//K8SAPIServerIPPort sets the IP:Port of Kubernetes api-server
	K8SAPIServerIPPort = "server"

	//CertPath sets the path of the certificates generated by the KubeEdge Cloud component
	CertPath = "certPath"

	//DefaultCertPath is the default certificate path in edge node
	DefaultCertPath = "/etc/kubeedge/certs"
)
