/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apisdevicesv1beta1 "github.com/kubeedge/api/apis/devices/v1beta1"
	versioned "github.com/kubeedge/api/client/clientset/versioned"
	internalinterfaces "github.com/kubeedge/api/client/informers/externalversions/internalinterfaces"
	devicesv1beta1 "github.com/kubeedge/api/client/listers/devices/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeviceStatusInformer provides access to a shared informer and lister for
// DeviceStatuses.
type DeviceStatusInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() devicesv1beta1.DeviceStatusLister
}

type deviceStatusInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeviceStatusInformer constructs a new informer for DeviceStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeviceStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeviceStatusInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeviceStatusInformer constructs a new informer for DeviceStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeviceStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DevicesV1beta1().DeviceStatuses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DevicesV1beta1().DeviceStatuses(namespace).Watch(context.TODO(), options)
			},
		},
		&apisdevicesv1beta1.DeviceStatus{},
		resyncPeriod,
		indexers,
	)
}

func (f *deviceStatusInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeviceStatusInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deviceStatusInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdevicesv1beta1.DeviceStatus{}, f.defaultInformer)
}

func (f *deviceStatusInformer) Lister() devicesv1beta1.DeviceStatusLister {
	return devicesv1beta1.NewDeviceStatusLister(f.Informer().GetIndexer())
}
