/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/kubeedge/api/apis/operations/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConfigUpdateJobs implements ConfigUpdateJobInterface
type FakeConfigUpdateJobs struct {
	Fake *FakeOperationsV1alpha2
}

var configupdatejobsResource = v1alpha2.SchemeGroupVersion.WithResource("configupdatejobs")

var configupdatejobsKind = v1alpha2.SchemeGroupVersion.WithKind("ConfigUpdateJob")

// Get takes name of the configUpdateJob, and returns the corresponding configUpdateJob object, and an error if there is any.
func (c *FakeConfigUpdateJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.ConfigUpdateJob, err error) {
	emptyResult := &v1alpha2.ConfigUpdateJob{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(configupdatejobsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.ConfigUpdateJob), err
}

// List takes label and field selectors, and returns the list of ConfigUpdateJobs that match those selectors.
func (c *FakeConfigUpdateJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.ConfigUpdateJobList, err error) {
	emptyResult := &v1alpha2.ConfigUpdateJobList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(configupdatejobsResource, configupdatejobsKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.ConfigUpdateJobList{ListMeta: obj.(*v1alpha2.ConfigUpdateJobList).ListMeta}
	for _, item := range obj.(*v1alpha2.ConfigUpdateJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested configUpdateJobs.
func (c *FakeConfigUpdateJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(configupdatejobsResource, opts))
}

// Create takes the representation of a configUpdateJob and creates it.  Returns the server's representation of the configUpdateJob, and an error, if there is any.
func (c *FakeConfigUpdateJobs) Create(ctx context.Context, configUpdateJob *v1alpha2.ConfigUpdateJob, opts v1.CreateOptions) (result *v1alpha2.ConfigUpdateJob, err error) {
	emptyResult := &v1alpha2.ConfigUpdateJob{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(configupdatejobsResource, configUpdateJob, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.ConfigUpdateJob), err
}

// Update takes the representation of a configUpdateJob and updates it. Returns the server's representation of the configUpdateJob, and an error, if there is any.
func (c *FakeConfigUpdateJobs) Update(ctx context.Context, configUpdateJob *v1alpha2.ConfigUpdateJob, opts v1.UpdateOptions) (result *v1alpha2.ConfigUpdateJob, err error) {
	emptyResult := &v1alpha2.ConfigUpdateJob{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(configupdatejobsResource, configUpdateJob, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.ConfigUpdateJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConfigUpdateJobs) UpdateStatus(ctx context.Context, configUpdateJob *v1alpha2.ConfigUpdateJob, opts v1.UpdateOptions) (result *v1alpha2.ConfigUpdateJob, err error) {
	emptyResult := &v1alpha2.ConfigUpdateJob{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(configupdatejobsResource, "status", configUpdateJob, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.ConfigUpdateJob), err
}

// Delete takes name of the configUpdateJob and deletes it. Returns an error if one occurs.
func (c *FakeConfigUpdateJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(configupdatejobsResource, name, opts), &v1alpha2.ConfigUpdateJob{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConfigUpdateJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(configupdatejobsResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.ConfigUpdateJobList{})
	return err
}

// Patch applies the patch and returns the patched configUpdateJob.
func (c *FakeConfigUpdateJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.ConfigUpdateJob, err error) {
	emptyResult := &v1alpha2.ConfigUpdateJob{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(configupdatejobsResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.ConfigUpdateJob), err
}
