name: Image Release

#only triggered when a new tag is created.
on:
  create:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    name: Buildx to build multi-arch images
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          make crossbuildimage
