name: Automated Test Generation

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install coverage tools
        run: |
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.1.0

      - name: Generate coverage report
        run: |
          go test -coverprofile=coverage.out ./...
          gocov convert coverage.out | gocov-xml > coverage.xml

      - name: Install Cover-Agent
        run: pip install git+https://github.com/Codium-ai/cover-agent.git

      - name: Set up DeepSeek API key
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: echo "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY" >> $GITHUB_ENV

      - name: Run Cover-Agent for low-coverage files
        run: |
          cover-agent \
            --source-file-path "app.go" \
            --test-file-path "app_test.go" \
            --code-coverage-report-path "coverage.xml" \
            --test-command "go test -coverprofile=coverage.out && gocov convert coverage.out | gocov-xml > coverage.xml" \
            --test-command-dir "$(pwd)" \
            --coverage-type "cobertura" \
            --desired-coverage 70 \
            --max-iterations 1 \
            --model "deepseek/deepseek-reasoner"

      - name: Commit generated tests
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *_test.go
          git commit -m "Add generated tests for low-coverage files"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Add automated tests for low-coverage code"
          body: "This PR contains tests generated by Cover-Agent using DeepSeek LLM."
          branch: "auto-generated-tests"
