# validate any chart changes under charts directory
name: Chart Lint

env:
  HELM_VERSION: v3.7.2
  KIND_VERSION: v0.11.1
  KIND_NODE_IMAGE: kindest/node:v1.23.4
  K8S_VERSION: v1.22.6

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "manifests/**"

jobs:
  chart-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v2.1
        with:
          version: ${{ env.HELM_VERSION }}

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.6.0

      - name: Run chart-testing (lint)
        run: ct lint --debug --check-version-increment=false --chart-dirs manifests/charts

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          wait: 120s
          version: ${{ env.KIND_VERSION }}
          node_image: ${{ env.KIND_NODE_IMAGE }}
          kubectl_version: ${{ env.K8S_VERSION }}

      - name: Run chart-testing (install)
        run: ct install --chart-dirs manifests/charts --debug --helm-extra-args "--timeout 400s"
